#ifndef CORE_META_DEFAULT_CONFIG
#define CORE_META_DEFAULT_CONFIG

#define CORE_MODS_DEFAULT_SCOPE public

#define CORE_ATOM_VIRTUALITY
#define CORE_ATOM_INHERITANCE public

#define CORE_MODS_ARCH_VIRTUALITY
#define CORE_MODS_ARCH_INHERITANCE public

#define CORE_MODS_DEFAULT_VIRTUALITY
#define CORE_MODS_DEFAULT_INHERITANCE public

#define ATOM_VIRTUALITY
#define ATOM_INHERITANCE public

#endif